#Fuente
font_family      CaskaydiaCove Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 20

#Colors
background_opacity 0.92
foreground #c5c9de
background #061119

  #black
  color0 #061119
  color8 #282a40

  #red
  color1 #cc0403
  color9 #f2201f

  #green
  color2  #2ac87e
  color10 #e0ffad

  #yellow
  color3  #cecb00
  color11 #fffd00

  #blue
  color4  #60d5ff
  color12 #1a8fff

  #magenta
  color5  #cb1ed1
  color13 #fd28ff

  #cyan
  color6  #60d5ff
  color14 #32c2f5

  #white
  color7  #bfd5de
  color15 #d1e5ed
